# Generated by Django 4.1.6 on 2023-04-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categories'),
        ),
        migrations.AddField(
            model_name='post',
            name='locations',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.DateTimeField(max_length=20, null=True),
        ),
    ]
