# Generated by Django 4.1.6 on 2023-02-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_review_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
