# Generated by Django 4.1.6 on 2023-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_post_status_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
