# Generated by Django 4.1.6 on 2023-03-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_professional_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
