# Generated by Django 4.1.6 on 2023-05-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_ispaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='locations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='booked_date',
            field=models.DateTimeField(max_length=20, null=True),
        ),
    ]
