# Generated by Django 4.1.6 on 2023-03-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='category',
        ),
    ]
