# Generated by Django 4.1.6 on 2023-03-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_professional_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
