# Generated by Django 4.1.6 on 2023-03-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
