# Generated by Django 4.1.6 on 2023-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
