# Generated by Django 4.1.6 on 2023-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
