# Generated by Django 4.1.6 on 2023-03-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_professional_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='rating',
        ),
    ]
