# Generated by Django 4.1.6 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_professional_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
