# Generated by Django 4.1.6 on 2023-03-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_professional_numreviews_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name_plural': 'Professionals'},
        ),
    ]
